### ISSUE TITLE
Privacy policy is unreadable - It's completely white

### ISSUE THREAD

**Issue by Dyras** [tholinka/Dark-Crunchyroll-Plugin#11]
**Please fill out the below information:**
**Describe the issue**
If you check out the privacy policy, it's completely white.

https://www.crunchyroll.com/privacy
![image](https://user-images.githubusercontent.com/12563436/74279258-dd915880-4d1a-11ea-904b-8df443b3a32b.png)

**Environment:**
  - Browser name: [Firefox]
  - Browser version: [72.0.2 64-bit)]
  - Addon version: [2.1.4]

**Comment by tholinka** [comment]
Thanks for the report, should be fixed in next version!
