### ISSUE TITLE
Feature request: usercss

### ISSUE THREAD

**Issue by z0rc** [tholinka/Dark-Crunchyroll-Plugin#12]
Installing the addon with bundled js is a bit too much just for style changes. Any chance to make this addon as usercss, so it can be installed with [Stylus](https://github.com/openstyles/stylus) or any other compatible addon?

**Comment by tholinka** [comment]
Okay, gulp should be able to export a usercss file now. I attached the current version, let me know if there are any issues!

The next release will include a usercss file in the "releases" section, which should hopefully auto update.  I'll look into adding it to userstyles.org at some point.

[dark-crunchroll.user.zip](https://github.com/tholinka/Dark-Crunchyroll-Plugin/files/4860519/dark-crunchroll.user.zip)
