### ISSUE TITLE
dark mode glitch

### ISSUE THREAD

**Issue by ShapedRogue** [tholinka/Dark-Crunchyroll-Plugin#15]
ok so the dark mode works perfectly fine and this is nitpicking but when you click on a link on crunchyroll it will go white for a second then into dark mode. this is especially annoying when clicking many differant links as it creates a sort of strobe light effect

**Comment by tholinka** [comment]
This is sadly unfixable.

We rely on the browser to inject the styles into the page, and the browser doesn't do that until after the page first loads.

I've tried to minimize the length of the white flash (several different times haha), but it is sadly impossible to completely remove it.
