### ISSUE TITLE
Logo resolution

### ISSUE THREAD

**Issue by kirayoru** [tholinka/Dark-Crunchyroll-Plugin#6]
First of all: This is a great extension and i love it! :D

If you can see it, the crunchyroll logo is a bit cut off at the left side & the resolution is really bad. I know this is just a luxery complain, but would be great if you could fix it ^^

![screenshot_2](https://user-images.githubusercontent.com/36333173/40312872-5b0dba7c-5d14-11e8-830f-7e8e21d6365f.png)

**Comment by kirayoru** [comment]
no

**Comment by tholinka** [comment]
This is either fixed or reproducible as of image changes in v2.0.2
