### ISSUE TITLE
white queue

### ISSUE THREAD

**Issue by Conando025** [tholinka/Dark-Crunchyroll-Plugin#8]
**Describe the issue**
The queue is plain white, which probably shouldn't be the case.

**Environment:**
  - Browser name: Firefox
  - Browser version: 72.0.2 (64-Bit)
  - Addon version: 2.1.3

**Note:**
The issue is independent of other addons.
![grafik](https://user-images.githubusercontent.com/37964708/72917157-97f8f580-3d43-11ea-8611-4c99ff6d552b.png)

**Comment by William1Gray** [comment]
Fixed in #9

**Comment by tholinka** [comment]
v2.1.4 is pushed to Chrome and Firefox stores and should be available as soon as they each approve them. Thanks for reporting this!
